// ═══════════════════════════════════════════
//  BLS International — Track Application
//  Public lookup: Appointment Number + Passport Number
//  Reads: visa_applications.tracking_stage (1-12), courier_opted
// ═══════════════════════════════════════════

// Same Supabase project used across the site (script.js / admin.js)
const SUPABASE_URL  = 'https://cnpuceqzubaolbfxqpge.supabase.co';
const SUPABASE_ANON = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNucHVjZXF6dWJhb2xiZnhxcGdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA5OTYxNzcsImV4cCI6MjA5NjU3MjE3N30.ZaxtjTXyVQIZytf3ChiCgr1tf-N7er2yqZ4pzv0za7E';

const supabaseConfigured = SUPABASE_URL !== 'YOUR_SUPABASE_URL';
let supabaseClient = null;
if (supabaseConfigured && typeof supabase !== 'undefined') {
  supabaseClient = supabase.createClient(SUPABASE_URL, SUPABASE_ANON);
}

// ── SAFETY NET ──────────────────────────────────────────────
// This file calls i18nT()/i18nInit()/i18nDateLocale() (defined in
// i18n-shared.js). If that file fails to load for any reason (wrong path,
// missing from the folder, network hiccup), those calls would throw
// "is not defined" and break the whole page. These fallbacks make sure
// that NEVER happens — worst case, translations just don't apply.
if (typeof i18nT !== 'function') {
  window.i18nT = function (key, fallback) { return fallback !== undefined ? fallback : key; };
  console.warn('i18n-shared.js did not load — check it is in the same folder as this page. Falling back to English.');
}
if (typeof i18nDateLocale !== 'function') {
  window.i18nDateLocale = function () { return 'en-IN'; };
}
if (typeof i18nInit !== 'function') {
  window.i18nInit = function () { /* no-op fallback */ };
}

document.addEventListener('DOMContentLoaded', () => {
  if (typeof i18nInit === 'function') i18nInit({ switcherEl: '#langSwitcher' });
});

// ── The 12 tracking stages ─────────────────────────────────────
// courier_opted decides the label/description for stage 12.
//
// SOURCE OF TRUTH: the `tracking_stage_config` table in Supabase.
// This local array is ONLY a fallback used if the config table can't
// be reached (e.g. offline), so the page still renders something sane.
// To change wording/icons, edit the table via the Admin panel —
// do NOT edit this file.
let TRACK_STEPS = [
  { stage: 1,  icon: 'fa-file-circle-check',   title: 'Application Submitted',    desc: 'Your visa application has been received by BLS International.' },
  { stage: 2,  icon: 'fa-hourglass-half',      title: 'Payment Pending',          desc: 'Application fee payment is awaited.' },
  { stage: 3,  icon: 'fa-credit-card',         title: 'Payment Submitted',        desc: 'Payment has been received and confirmed.' },
  { stage: 4,  icon: 'fa-hourglass-half',      title: 'Biometric Pending',        desc: 'Biometric appointment is yet to be completed.' },
  { stage: 5,  icon: 'fa-fingerprint',         title: 'Biometric Submitted',      desc: 'Biometrics (photo &amp; fingerprints) have been captured.' },
  { stage: 6,  icon: 'fa-file-export',         title: 'Acuta Pending',            desc: 'Application form &amp; documents are being prepared to be sent to the Embassy.' },
  { stage: 7,  icon: 'fa-check-double',        title: 'Acuta Submitted',          desc: 'Application file has been finalised and is ready for dispatch to the Embassy.' },
  { stage: 8,  icon: 'fa-arrow-up-right-from-square', title: 'Outscan to Mission', desc: 'File has been dispatched from BLS to the Embassy / Mission.' },
  { stage: 9,  icon: 'fa-building-flag',       title: 'Inscan at Embassy',        desc: 'File has been received and logged at the Embassy.' },
  { stage: 10, icon: 'fa-arrow-rotate-left',   title: 'Outscan to BLS',           desc: 'Embassy has dispatched the file back to BLS International.' },
  { stage: 11, icon: 'fa-warehouse',           title: 'Inscan at BLS',            desc: 'File has been received back and logged at BLS International.' },
  { stage: 12, icon: 'fa-truck',               title: 'Outscan to Courier',       desc: 'Passport / visa has been handed over for courier delivery.',
               titleAlt: 'Ready for Pickup',   descAlt: 'Passport / visa is ready for self collection at the BLS centre.' },
];

// Loads TRACK_STEPS from the tracking_stage_config table. Falls back to
// the hardcoded defaults above if the table is empty/unreachable.
let stageConfigPromise = null;
function loadStageConfig() {
  if (stageConfigPromise) return stageConfigPromise; // cache — only fetch once per page load
  stageConfigPromise = (async () => {
    if (!supabaseClient) return;
    try {
      const { data, error } = await supabaseClient
        .from('tracking_stage_config')
        .select('stage, icon, title, description, title_alt, description_alt')
        .eq('active', true)
        .order('stage', { ascending: true });

      if (error) throw error;
      if (data && data.length) {
        // Merge in translated titles/descriptions for the current site language
        // (see i18n-shared.js), falling back to the base English columns.
        let langCode = null;
        try { langCode = localStorage.getItem('bls_site_lang'); } catch (e) { /* ignore */ }
        let transByStage = {};
        if (langCode && langCode !== 'en') {
          try {
            const { data: trans } = await supabaseClient
              .from('tracking_stage_translations')
              .select('stage, title, description, title_alt, description_alt')
              .eq('language_code', langCode);
            (trans || []).forEach(t => { transByStage[t.stage] = t; });
          } catch (e) {
            console.warn('tracking_stage_translations lookup failed (non-fatal):', e);
          }
        }

        TRACK_STEPS = data.map(row => {
          const t = transByStage[row.stage];
          return {
            stage: row.stage,
            icon: row.icon || 'fa-circle',
            title: (t && t.title) || row.title,
            desc: (t && t.description) || row.description || '',
            titleAlt: (t && t.title_alt) || row.title_alt || undefined,
            descAlt: (t && t.description_alt) || row.description_alt || undefined,
          };
        });
      }
    } catch (e) {
      console.warn('Could not load tracking_stage_config, using fallback labels', e);
    }
  })();
  return stageConfigPromise;
}
// Kick it off immediately so it's ready (or already cached) by the time the user clicks Track.
loadStageConfig();

function stepLabel(step, courierOpted) {
  if (step.stage === 12) return courierOpted ? step.title : step.titleAlt;
  return step.title;
}
function stepDesc(step, courierOpted) {
  if (step.stage === 12) return courierOpted ? step.desc : step.descAlt;
  return step.desc;
}

function $(id) { return document.getElementById(id); }

function showLookupError(msg) {
  $('lookupMsgText').textContent = msg;
  $('lookupMsg').classList.add('show');
}
function hideLookupError() {
  $('lookupMsg').classList.remove('show');
}

window.resetLookup = function () {
  $('resultWrap').style.display = 'none';
  $('refInput').value = '';
  $('passportInput').value = '';
  hideLookupError();
  $('refInput').focus();
};

function fmtDate(d) {
  if (!d) return '—';
  try {
    return new Date(d).toLocaleDateString(i18nDateLocale(), { day: '2-digit', month: 'short', year: 'numeric' });
  } catch (e) { return d; }
}

window.trackApplication = async function () {
  hideLookupError();

  const ref = $('refInput').value.trim().toUpperCase();
  const passport = $('passportInput').value.trim().toUpperCase();

  if (!ref) { showLookupError(i18nT('track.err.no_ref', 'Please enter your Appointment Number.')); $('refInput').focus(); return; }
  if (!passport) { showLookupError(i18nT('track.err.no_passport', 'Please enter your Passport Number.')); $('passportInput').focus(); return; }

  const btn = $('trackBtn');
  btn.disabled = true;
  btn.innerHTML = '<i class="fa fa-spinner fa-spin"></i> Searching...';

  try {
    const res = await fetch(
      `http://localhost:5000/api/users/visa/track/${encodeURIComponent(ref)}/${encodeURIComponent(passport)}`
    );
    const result = await res.json();

    if (!res.ok) throw new Error(result.error || 'Lookup failed');

    const data = result.application;

    if (!data) {
      showLookupError(i18nT('track.err.not_found', 'No application found. Please check your Appointment Number and Passport Number and try again.'));
      return;
    }

    await loadStageConfig(); // make sure master stage labels are in before rendering
    renderResult(data);
  } catch (err) {
    console.error('Track lookup error:', err);
    showLookupError(i18nT('track.err.generic', 'Something went wrong while searching. Please try again in a moment.'));
  } finally {
    btn.disabled = false;
    btn.innerHTML = '<i class="fa fa-magnifying-glass"></i> Track';
  }
};

function renderResult(d) {
  const currentStage = Math.min(Math.max(parseInt(d.tracking_stage, 10) || 1, 1), 12);
  const courierOpted = !!d.courier_opted;

  $('rsName').textContent = d.full_name || '—';
  $('rsRef').textContent = d.reference_number || '—';
  $('rsVisaType').textContent = d.purpose_of_visit || '—';
  $('rsDestination').textContent = d.destination_country || '—';
  $('rsSubmitted').textContent = fmtDate(d.created_at);

  const currentStep = TRACK_STEPS.find(s => s.stage === currentStage);
  $('rsStatusPill').textContent = stepLabel(currentStep, courierOpted);
  $('rsStatusPill').style.background = currentStage === 12 ? 'var(--green)' : 'var(--gold)';

  const list = $('timelineList');
  list.innerHTML = TRACK_STEPS.map(step => {
    const isDone = step.stage <= currentStage;
    const isCurrent = step.stage === currentStage;
    const label = stepLabel(step, courierOpted);
    const desc = stepDesc(step, courierOpted);
    return `
      <div class="tl-step ${isDone ? 'is-done' : ''}">
        <div class="tl-line ${step.stage < currentStage ? 'done' : ''}"></div>
        <div class="tl-circle ${isDone ? 'done' : ''} ${isCurrent ? 'current' : ''}">
          <i class="fa ${isDone ? 'fa-check' : step.icon}"></i>
        </div>
        <div class="tl-body">
          <div class="tl-title">${step.stage}. ${label}</div>
          <div class="tl-desc">${desc}</div>
          ${isCurrent ? '<span class="tl-current-tag"><i class="fa fa-circle-dot"></i> Current Stage</span>' : ''}
        </div>
      </div>`;
  }).join('');

  $('resultWrap').style.display = 'block';
  $('resultWrap').scrollIntoView({ behavior: 'smooth', block: 'start' });
}